---
apiVersion: v1
kind: ReplicationController
metadata:
  name: test-pod
spec:
  replicas: 3
  selector:
    app: test-pod
  template:
    metadata:
      name: test-pod
      labels:
        app: test-pod
    spec:
      containers:
      - name: test-pod
        image: gcr.io/google_containers/pause
        resources:
          requests:
            cpu: 150m
            memory: 100Mi
        ports:
        - containerPort: 80
